package id.co.icg.reload.util;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import id.co.icg.reload.model.Tuple;

public class CityRegencies {

    private static Map<String,List<Tuple>> cityRegencies = new TreeMap<>();

    static {
        List<Tuple> list = new ArrayList<>();
        list.add(new Tuple("1101","KABUPATEN SIMEULUE"));
        list.add(new Tuple("1102","KABUPATEN ACEH SINGKIL"));
        list.add(new Tuple("1103","KABUPATEN ACEH SELATAN"));
        list.add(new Tuple("1104","KABUPATEN ACEH TENGGARA"));
        list.add(new Tuple("1105","KABUPATEN ACEH TIMUR"));
        list.add(new Tuple("1106","KABUPATEN ACEH TENGAH"));
        list.add(new Tuple("1107","KABUPATEN ACEH BARAT"));
        list.add(new Tuple("1108","KABUPATEN ACEH BESAR"));
        list.add(new Tuple("1109","KABUPATEN PIDIE"));
        list.add(new Tuple("1110","KABUPATEN BIREUEN"));
        list.add(new Tuple("1111","KABUPATEN ACEH UTARA"));
        list.add(new Tuple("1112","KABUPATEN ACEH BARAT DAYA"));
        list.add(new Tuple("1113","KABUPATEN GAYO LUES"));
        list.add(new Tuple("1114","KABUPATEN ACEH TAMIANG"));
        list.add(new Tuple("1115","KABUPATEN NAGAN RAYA"));
        list.add(new Tuple("1116","KABUPATEN ACEH JAYA"));
        list.add(new Tuple("1117","KABUPATEN BENER MERIAH"));
        list.add(new Tuple("1118","KABUPATEN PIDIE JAYA"));
        list.add(new Tuple("1171","KOTA BANDA ACEH"));
        list.add(new Tuple("1172","KOTA SABANG"));
        list.add(new Tuple("1173","KOTA LANGSA"));
        list.add(new Tuple("1174","KOTA LHOKSEUMAWE"));
        list.add(new Tuple("1175","KOTA SUBULUSSALAM"));
        cityRegencies.put("11", list);

        list = new ArrayList<>();
        list.add(new Tuple("1201","KABUPATEN NIAS"));
        list.add(new Tuple("1202","KABUPATEN MANDAILING NATAL"));
        list.add(new Tuple("1203","KABUPATEN TAPANULI SELATAN"));
        list.add(new Tuple("1204","KABUPATEN TAPANULI TENGAH"));
        list.add(new Tuple("1205","KABUPATEN TAPANULI UTARA"));
        list.add(new Tuple("1206","KABUPATEN TOBA SAMOSIR"));
        list.add(new Tuple("1207","KABUPATEN LABUHAN BATU"));
        list.add(new Tuple("1208","KABUPATEN ASAHAN"));
        list.add(new Tuple("1209","KABUPATEN SIMALUNGUN"));
        list.add(new Tuple("1210","KABUPATEN DAIRI"));
        list.add(new Tuple("1211","KABUPATEN KARO"));
        list.add(new Tuple("1212","KABUPATEN DELI SERDANG"));
        list.add(new Tuple("1213","KABUPATEN LANGKAT"));
        list.add(new Tuple("1214","KABUPATEN NIAS SELATAN"));
        list.add(new Tuple("1215","KABUPATEN HUMBANG HASUNDUTAN"));
        list.add(new Tuple("1216","KABUPATEN PAKPAK BHARAT"));
        list.add(new Tuple("1217","KABUPATEN SAMOSIR"));
        list.add(new Tuple("1218","KABUPATEN SERDANG BEDAGAI"));
        list.add(new Tuple("1219","KABUPATEN BATU BARA"));
        list.add(new Tuple("1220","KABUPATEN PADANG LAWAS UTARA"));
        list.add(new Tuple("1221","KABUPATEN PADANG LAWAS"));
        list.add(new Tuple("1222","KABUPATEN LABUHAN BATU SELATAN"));
        list.add(new Tuple("1223","KABUPATEN LABUHAN BATU UTARA"));
        list.add(new Tuple("1224","KABUPATEN NIAS UTARA"));
        list.add(new Tuple("1225","KABUPATEN NIAS BARAT"));
        list.add(new Tuple("1271","KOTA SIBOLGA"));
        list.add(new Tuple("1272","KOTA TANJUNG BALAI"));
        list.add(new Tuple("1273","KOTA PEMATANG SIANTAR"));
        list.add(new Tuple("1274","KOTA TEBING TINGGI"));
        list.add(new Tuple("1275","KOTA MEDAN"));
        list.add(new Tuple("1276","KOTA BINJAI"));
        list.add(new Tuple("1277","KOTA PADANGSIDIMPUAN"));
        list.add(new Tuple("1278","KOTA GUNUNGSITOLI"));
        cityRegencies.put("12", list);

        list = new ArrayList<>();
        list.add(new Tuple("1301","KABUPATEN KEPULAUAN MENTAWAI"));
        list.add(new Tuple("1302","KABUPATEN PESISIR SELATAN"));
        list.add(new Tuple("1303","KABUPATEN SOLOK"));
        list.add(new Tuple("1304","KABUPATEN SIJUNJUNG"));
        list.add(new Tuple("1305","KABUPATEN TANAH DATAR"));
        list.add(new Tuple("1306","KABUPATEN PADANG PARIAMAN"));
        list.add(new Tuple("1307","KABUPATEN AGAM"));
        list.add(new Tuple("1308","KABUPATEN LIMA PULUH KOTA"));
        list.add(new Tuple("1309","KABUPATEN PASAMAN"));
        list.add(new Tuple("1310","KABUPATEN SOLOK SELATAN"));
        list.add(new Tuple("1311","KABUPATEN DHARMASRAYA"));
        list.add(new Tuple("1312","KABUPATEN PASAMAN BARAT"));
        list.add(new Tuple("1371","KOTA PADANG"));
        list.add(new Tuple("1372","KOTA SOLOK"));
        list.add(new Tuple("1373","KOTA SAWAH LUNTO"));
        list.add(new Tuple("1374","KOTA PADANG PANJANG"));
        list.add(new Tuple("1375","KOTA BUKITTINGGI"));
        list.add(new Tuple("1376","KOTA PAYAKUMBUH"));
        list.add(new Tuple("1377","KOTA PARIAMAN"));
        cityRegencies.put("13", list);

        list = new ArrayList<>();
        list.add(new Tuple("1401","KABUPATEN KUANTAN SINGINGI"));
        list.add(new Tuple("1402","KABUPATEN INDRAGIRI HULU"));
        list.add(new Tuple("1403","KABUPATEN INDRAGIRI HILIR"));
        list.add(new Tuple("1404","KABUPATEN PELALAWAN"));
        list.add(new Tuple("1405","KABUPATEN S I A K"));
        list.add(new Tuple("1406","KABUPATEN KAMPAR"));
        list.add(new Tuple("1407","KABUPATEN ROKAN HULU"));
        list.add(new Tuple("1408","KABUPATEN BENGKALIS"));
        list.add(new Tuple("1409","KABUPATEN ROKAN HILIR"));
        list.add(new Tuple("1410","KABUPATEN KEPULAUAN MERANTI"));
        list.add(new Tuple("1471","KOTA PEKANBARU"));
        list.add(new Tuple("1473","KOTA D U M A I"));
        cityRegencies.put("14", list);

        list = new ArrayList<>();
        list.add(new Tuple("1501","KABUPATEN KERINCI"));
        list.add(new Tuple("1502","KABUPATEN MERANGIN"));
        list.add(new Tuple("1503","KABUPATEN SAROLANGUN"));
        list.add(new Tuple("1504","KABUPATEN BATANG HARI"));
        list.add(new Tuple("1505","KABUPATEN MUARO JAMBI"));
        list.add(new Tuple("1506","KABUPATEN TANJUNG JABUNG TIMUR"));
        list.add(new Tuple("1507","KABUPATEN TANJUNG JABUNG BARAT"));
        list.add(new Tuple("1508","KABUPATEN TEBO"));
        list.add(new Tuple("1509","KABUPATEN BUNGO"));
        list.add(new Tuple("1571","KOTA JAMBI"));
        list.add(new Tuple("1572","KOTA SUNGAI PENUH"));
        cityRegencies.put("15", list);

        list = new ArrayList<>();
        list.add(new Tuple("1601","KABUPATEN OGAN KOMERING ULU"));
        list.add(new Tuple("1602","KABUPATEN OGAN KOMERING ILIR"));
        list.add(new Tuple("1603","KABUPATEN MUARA ENIM"));
        list.add(new Tuple("1604","KABUPATEN LAHAT"));
        list.add(new Tuple("1605","KABUPATEN MUSI RAWAS"));
        list.add(new Tuple("1606","KABUPATEN MUSI BANYUASIN"));
        list.add(new Tuple("1607","KABUPATEN BANYU ASIN"));
        list.add(new Tuple("1608","KABUPATEN OGAN KOMERING ULU SELATAN"));
        list.add(new Tuple("1609","KABUPATEN OGAN KOMERING ULU TIMUR"));
        list.add(new Tuple("1610","KABUPATEN OGAN ILIR"));
        list.add(new Tuple("1611","KABUPATEN EMPAT LAWANG"));
        list.add(new Tuple("1612","KABUPATEN PENUKAL ABAB LEMATANG ILIR"));
        list.add(new Tuple("1613","KABUPATEN MUSI RAWAS UTARA"));
        list.add(new Tuple("1671","KOTA PALEMBANG"));
        list.add(new Tuple("1672","KOTA PRABUMULIH"));
        list.add(new Tuple("1673","KOTA PAGAR ALAM"));
        list.add(new Tuple("1674","KOTA LUBUKLINGGAU"));
        cityRegencies.put("16", list);

        list = new ArrayList<>();
        list.add(new Tuple("1701","KABUPATEN BENGKULU SELATAN"));
        list.add(new Tuple("1702","KABUPATEN REJANG LEBONG"));
        list.add(new Tuple("1703","KABUPATEN BENGKULU UTARA"));
        list.add(new Tuple("1704","KABUPATEN KAUR"));
        list.add(new Tuple("1705","KABUPATEN SELUMA"));
        list.add(new Tuple("1706","KABUPATEN MUKOMUKO"));
        list.add(new Tuple("1707","KABUPATEN LEBONG"));
        list.add(new Tuple("1708","KABUPATEN KEPAHIANG"));
        list.add(new Tuple("1709","KABUPATEN BENGKULU TENGAH"));
        list.add(new Tuple("1771","KOTA BENGKULU"));
        cityRegencies.put("17", list);

        list = new ArrayList<>();
        list.add(new Tuple("1801","KABUPATEN LAMPUNG BARAT"));
        list.add(new Tuple("1802","KABUPATEN TANGGAMUS"));
        list.add(new Tuple("1803","KABUPATEN LAMPUNG SELATAN"));
        list.add(new Tuple("1804","KABUPATEN LAMPUNG TIMUR"));
        list.add(new Tuple("1805","KABUPATEN LAMPUNG TENGAH"));
        list.add(new Tuple("1806","KABUPATEN LAMPUNG UTARA"));
        list.add(new Tuple("1807","KABUPATEN WAY KANAN"));
        list.add(new Tuple("1808","KABUPATEN TULANGBAWANG"));
        list.add(new Tuple("1809","KABUPATEN PESAWARAN"));
        list.add(new Tuple("1810","KABUPATEN PRINGSEWU"));
        list.add(new Tuple("1811","KABUPATEN MESUJI"));
        list.add(new Tuple("1812","KABUPATEN TULANG BAWANG BARAT"));
        list.add(new Tuple("1813","KABUPATEN PESISIR BARAT"));
        list.add(new Tuple("1871","KOTA BANDAR LAMPUNG"));
        list.add(new Tuple("1872","KOTA METRO"));
        cityRegencies.put("18", list);

        list = new ArrayList<>();
        list.add(new Tuple("1901","KABUPATEN BANGKA"));
        list.add(new Tuple("1902","KABUPATEN BELITUNG"));
        list.add(new Tuple("1903","KABUPATEN BANGKA BARAT"));
        list.add(new Tuple("1904","KABUPATEN BANGKA TENGAH"));
        list.add(new Tuple("1905","KABUPATEN BANGKA SELATAN"));
        list.add(new Tuple("1906","KABUPATEN BELITUNG TIMUR"));
        list.add(new Tuple("1971","KOTA PANGKAL PINANG"));
        cityRegencies.put("19", list);

        list = new ArrayList<>();
        list.add(new Tuple("2101","KABUPATEN KARIMUN"));
        list.add(new Tuple("2102","KABUPATEN BINTAN"));
        list.add(new Tuple("2103","KABUPATEN NATUNA"));
        list.add(new Tuple("2104","KABUPATEN LINGGA"));
        list.add(new Tuple("2105","KABUPATEN KEPULAUAN ANAMBAS"));
        list.add(new Tuple("2171","KOTA B A T A M"));
        list.add(new Tuple("2172","KOTA TANJUNG PINANG"));
        cityRegencies.put("21", list);

        list = new ArrayList<>();
        list.add(new Tuple("3101","KABUPATEN KEPULAUAN SERIBU"));
        list.add(new Tuple("3171","KOTA JAKARTA SELATAN"));
        list.add(new Tuple("3172","KOTA JAKARTA TIMUR"));
        list.add(new Tuple("3173","KOTA JAKARTA PUSAT"));
        list.add(new Tuple("3174","KOTA JAKARTA BARAT"));
        list.add(new Tuple("3175","KOTA JAKARTA UTARA"));
        cityRegencies.put("31", list);

        list = new ArrayList<>();
        list.add(new Tuple("3201","KABUPATEN BOGOR"));
        list.add(new Tuple("3202","KABUPATEN SUKABUMI"));
        list.add(new Tuple("3203","KABUPATEN CIANJUR"));
        list.add(new Tuple("3204","KABUPATEN BANDUNG"));
        list.add(new Tuple("3205","KABUPATEN GARUT"));
        list.add(new Tuple("3206","KABUPATEN TASIKMALAYA"));
        list.add(new Tuple("3207","KABUPATEN CIAMIS"));
        list.add(new Tuple("3208","KABUPATEN KUNINGAN"));
        list.add(new Tuple("3209","KABUPATEN CIREBON"));
        list.add(new Tuple("3210","KABUPATEN MAJALENGKA"));
        list.add(new Tuple("3211","KABUPATEN SUMEDANG"));
        list.add(new Tuple("3212","KABUPATEN INDRAMAYU"));
        list.add(new Tuple("3213","KABUPATEN SUBANG"));
        list.add(new Tuple("3214","KABUPATEN PURWAKARTA"));
        list.add(new Tuple("3215","KABUPATEN KARAWANG"));
        list.add(new Tuple("3216","KABUPATEN BEKASI"));
        list.add(new Tuple("3217","KABUPATEN BANDUNG BARAT"));
        list.add(new Tuple("3218","KABUPATEN PANGANDARAN"));
        list.add(new Tuple("3271","KOTA BOGOR"));
        list.add(new Tuple("3272","KOTA SUKABUMI"));
        list.add(new Tuple("3273","KOTA BANDUNG"));
        list.add(new Tuple("3274","KOTA CIREBON"));
        list.add(new Tuple("3275","KOTA BEKASI"));
        list.add(new Tuple("3276","KOTA DEPOK"));
        list.add(new Tuple("3277","KOTA CIMAHI"));
        list.add(new Tuple("3278","KOTA TASIKMALAYA"));
        list.add(new Tuple("3279","KOTA BANJAR"));
        cityRegencies.put("32", list);

        list = new ArrayList<>();
        list.add(new Tuple("3301","KABUPATEN CILACAP"));
        list.add(new Tuple("3302","KABUPATEN BANYUMAS"));
        list.add(new Tuple("3303","KABUPATEN PURBALINGGA"));
        list.add(new Tuple("3304","KABUPATEN BANJARNEGARA"));
        list.add(new Tuple("3305","KABUPATEN KEBUMEN"));
        list.add(new Tuple("3306","KABUPATEN PURWOREJO"));
        list.add(new Tuple("3307","KABUPATEN WONOSOBO"));
        list.add(new Tuple("3308","KABUPATEN MAGELANG"));
        list.add(new Tuple("3309","KABUPATEN BOYOLALI"));
        list.add(new Tuple("3310","KABUPATEN KLATEN"));
        list.add(new Tuple("3311","KABUPATEN SUKOHARJO"));
        list.add(new Tuple("3312","KABUPATEN WONOGIRI"));
        list.add(new Tuple("3313","KABUPATEN KARANGANYAR"));
        list.add(new Tuple("3314","KABUPATEN SRAGEN"));
        list.add(new Tuple("3315","KABUPATEN GROBOGAN"));
        list.add(new Tuple("3316","KABUPATEN BLORA"));
        list.add(new Tuple("3317","KABUPATEN REMBANG"));
        list.add(new Tuple("3318","KABUPATEN PATI"));
        list.add(new Tuple("3319","KABUPATEN KUDUS"));
        list.add(new Tuple("3320","KABUPATEN JEPARA"));
        list.add(new Tuple("3321","KABUPATEN DEMAK"));
        list.add(new Tuple("3322","KABUPATEN SEMARANG"));
        list.add(new Tuple("3323","KABUPATEN TEMANGGUNG"));
        list.add(new Tuple("3324","KABUPATEN KENDAL"));
        list.add(new Tuple("3325","KABUPATEN BATANG"));
        list.add(new Tuple("3326","KABUPATEN PEKALONGAN"));
        list.add(new Tuple("3327","KABUPATEN PEMALANG"));
        list.add(new Tuple("3328","KABUPATEN TEGAL"));
        list.add(new Tuple("3329","KABUPATEN BREBES"));
        list.add(new Tuple("3371","KOTA MAGELANG"));
        list.add(new Tuple("3372","KOTA SURAKARTA"));
        list.add(new Tuple("3373","KOTA SALATIGA"));
        list.add(new Tuple("3374","KOTA SEMARANG"));
        list.add(new Tuple("3375","KOTA PEKALONGAN"));
        list.add(new Tuple("3376","KOTA TEGAL"));
        cityRegencies.put("33", list);

        list = new ArrayList<>();
        list.add(new Tuple("3401","KABUPATEN KULON PROGO"));
        list.add(new Tuple("3402","KABUPATEN BANTUL"));
        list.add(new Tuple("3403","KABUPATEN GUNUNG KIDUL"));
        list.add(new Tuple("3404","KABUPATEN SLEMAN"));
        list.add(new Tuple("3471","KOTA YOGYAKARTA"));
        cityRegencies.put("34", list);

        list = new ArrayList<>();
        list.add(new Tuple("3501","KABUPATEN PACITAN"));
        list.add(new Tuple("3502","KABUPATEN PONOROGO"));
        list.add(new Tuple("3503","KABUPATEN TRENGGALEK"));
        list.add(new Tuple("3504","KABUPATEN TULUNGAGUNG"));
        list.add(new Tuple("3505","KABUPATEN BLITAR"));
        list.add(new Tuple("3506","KABUPATEN KEDIRI"));
        list.add(new Tuple("3507","KABUPATEN MALANG"));
        list.add(new Tuple("3508","KABUPATEN LUMAJANG"));
        list.add(new Tuple("3509","KABUPATEN JEMBER"));
        list.add(new Tuple("3510","KABUPATEN BANYUWANGI"));
        list.add(new Tuple("3511","KABUPATEN BONDOWOSO"));
        list.add(new Tuple("3512","KABUPATEN SITUBONDO"));
        list.add(new Tuple("3513","KABUPATEN PROBOLINGGO"));
        list.add(new Tuple("3514","KABUPATEN PASURUAN"));
        list.add(new Tuple("3515","KABUPATEN SIDOARJO"));
        list.add(new Tuple("3516","KABUPATEN MOJOKERTO"));
        list.add(new Tuple("3517","KABUPATEN JOMBANG"));
        list.add(new Tuple("3518","KABUPATEN NGANJUK"));
        list.add(new Tuple("3519","KABUPATEN MADIUN"));
        list.add(new Tuple("3520","KABUPATEN MAGETAN"));
        list.add(new Tuple("3521","KABUPATEN NGAWI"));
        list.add(new Tuple("3522","KABUPATEN BOJONEGORO"));
        list.add(new Tuple("3523","KABUPATEN TUBAN"));
        list.add(new Tuple("3524","KABUPATEN LAMONGAN"));
        list.add(new Tuple("3525","KABUPATEN GRESIK"));
        list.add(new Tuple("3526","KABUPATEN BANGKALAN"));
        list.add(new Tuple("3527","KABUPATEN SAMPANG"));
        list.add(new Tuple("3528","KABUPATEN PAMEKASAN"));
        list.add(new Tuple("3529","KABUPATEN SUMENEP"));
        list.add(new Tuple("3571","KOTA KEDIRI"));
        list.add(new Tuple("3572","KOTA BLITAR"));
        list.add(new Tuple("3573","KOTA MALANG"));
        list.add(new Tuple("3574","KOTA PROBOLINGGO"));
        list.add(new Tuple("3575","KOTA PASURUAN"));
        list.add(new Tuple("3576","KOTA MOJOKERTO"));
        list.add(new Tuple("3577","KOTA MADIUN"));
        list.add(new Tuple("3578","KOTA SURABAYA"));
        list.add(new Tuple("3579","KOTA BATU"));
        cityRegencies.put("35", list);

        list = new ArrayList<>();
        list.add(new Tuple("3601","KABUPATEN PANDEGLANG"));
        list.add(new Tuple("3602","KABUPATEN LEBAK"));
        list.add(new Tuple("3603","KABUPATEN TANGERANG"));
        list.add(new Tuple("3604","KABUPATEN SERANG"));
        list.add(new Tuple("3671","KOTA TANGERANG"));
        list.add(new Tuple("3672","KOTA CILEGON"));
        list.add(new Tuple("3673","KOTA SERANG"));
        list.add(new Tuple("3674","KOTA TANGERANG SELATAN"));
        cityRegencies.put("36", list);

        list = new ArrayList<>();
        list.add(new Tuple("5101","KABUPATEN JEMBRANA"));
        list.add(new Tuple("5102","KABUPATEN TABANAN"));
        list.add(new Tuple("5103","KABUPATEN BADUNG"));
        list.add(new Tuple("5104","KABUPATEN GIANYAR"));
        list.add(new Tuple("5105","KABUPATEN KLUNGKUNG"));
        list.add(new Tuple("5106","KABUPATEN BANGLI"));
        list.add(new Tuple("5107","KABUPATEN KARANG ASEM"));
        list.add(new Tuple("5108","KABUPATEN BULELENG"));
        list.add(new Tuple("5171","KOTA DENPASAR"));
        cityRegencies.put("51", list);

        list = new ArrayList<>();
        list.add(new Tuple("5201","KABUPATEN LOMBOK BARAT"));
        list.add(new Tuple("5202","KABUPATEN LOMBOK TENGAH"));
        list.add(new Tuple("5203","KABUPATEN LOMBOK TIMUR"));
        list.add(new Tuple("5204","KABUPATEN SUMBAWA"));
        list.add(new Tuple("5205","KABUPATEN DOMPU"));
        list.add(new Tuple("5206","KABUPATEN BIMA"));
        list.add(new Tuple("5207","KABUPATEN SUMBAWA BARAT"));
        list.add(new Tuple("5208","KABUPATEN LOMBOK UTARA"));
        list.add(new Tuple("5271","KOTA MATARAM"));
        list.add(new Tuple("5272","KOTA BIMA"));
        cityRegencies.put("52", list);

        list = new ArrayList<>();
        list.add(new Tuple("5301","KABUPATEN SUMBA BARAT"));
        list.add(new Tuple("5302","KABUPATEN SUMBA TIMUR"));
        list.add(new Tuple("5303","KABUPATEN KUPANG"));
        list.add(new Tuple("5304","KABUPATEN TIMOR TENGAH SELATAN"));
        list.add(new Tuple("5305","KABUPATEN TIMOR TENGAH UTARA"));
        list.add(new Tuple("5306","KABUPATEN BELU"));
        list.add(new Tuple("5307","KABUPATEN ALOR"));
        list.add(new Tuple("5308","KABUPATEN LEMBATA"));
        list.add(new Tuple("5309","KABUPATEN FLORES TIMUR"));
        list.add(new Tuple("5310","KABUPATEN SIKKA"));
        list.add(new Tuple("5311","KABUPATEN ENDE"));
        list.add(new Tuple("5312","KABUPATEN NGADA"));
        list.add(new Tuple("5313","KABUPATEN MANGGARAI"));
        list.add(new Tuple("5314","KABUPATEN ROTE NDAO"));
        list.add(new Tuple("5315","KABUPATEN MANGGARAI BARAT"));
        list.add(new Tuple("5316","KABUPATEN SUMBA TENGAH"));
        list.add(new Tuple("5317","KABUPATEN SUMBA BARAT DAYA"));
        list.add(new Tuple("5318","KABUPATEN NAGEKEO"));
        list.add(new Tuple("5319","KABUPATEN MANGGARAI TIMUR"));
        list.add(new Tuple("5320","KABUPATEN SABU RAIJUA"));
        list.add(new Tuple("5321","KABUPATEN MALAKA"));
        list.add(new Tuple("5371","KOTA KUPANG"));
        cityRegencies.put("53", list);

        list = new ArrayList<>();
        list.add(new Tuple("6101","KABUPATEN SAMBAS"));
        list.add(new Tuple("6102","KABUPATEN BENGKAYANG"));
        list.add(new Tuple("6103","KABUPATEN LANDAK"));
        list.add(new Tuple("6104","KABUPATEN MEMPAWAH"));
        list.add(new Tuple("6105","KABUPATEN SANGGAU"));
        list.add(new Tuple("6106","KABUPATEN KETAPANG"));
        list.add(new Tuple("6107","KABUPATEN SINTANG"));
        list.add(new Tuple("6108","KABUPATEN KAPUAS HULU"));
        list.add(new Tuple("6109","KABUPATEN SEKADAU"));
        list.add(new Tuple("6110","KABUPATEN MELAWI"));
        list.add(new Tuple("6111","KABUPATEN KAYONG UTARA"));
        list.add(new Tuple("6112","KABUPATEN KUBU RAYA"));
        list.add(new Tuple("6171","KOTA PONTIANAK"));
        list.add(new Tuple("6172","KOTA SINGKAWANG"));
        cityRegencies.put("61", list);

        list = new ArrayList<>();
        list.add(new Tuple("6201","KABUPATEN KOTAWARINGIN BARAT"));
        list.add(new Tuple("6202","KABUPATEN KOTAWARINGIN TIMUR"));
        list.add(new Tuple("6203","KABUPATEN KAPUAS"));
        list.add(new Tuple("6204","KABUPATEN BARITO SELATAN"));
        list.add(new Tuple("6205","KABUPATEN BARITO UTARA"));
        list.add(new Tuple("6206","KABUPATEN SUKAMARA"));
        list.add(new Tuple("6207","KABUPATEN LAMANDAU"));
        list.add(new Tuple("6208","KABUPATEN SERUYAN"));
        list.add(new Tuple("6209","KABUPATEN KATINGAN"));
        list.add(new Tuple("6210","KABUPATEN PULANG PISAU"));
        list.add(new Tuple("6211","KABUPATEN GUNUNG MAS"));
        list.add(new Tuple("6212","KABUPATEN BARITO TIMUR"));
        list.add(new Tuple("6213","KABUPATEN MURUNG RAYA"));
        list.add(new Tuple("6271","KOTA PALANGKA RAYA"));
        cityRegencies.put("62", list);

        list = new ArrayList<>();
        list.add(new Tuple("6301","KABUPATEN TANAH LAUT"));
        list.add(new Tuple("6302","KABUPATEN KOTA BARU"));
        list.add(new Tuple("6303","KABUPATEN BANJAR"));
        list.add(new Tuple("6304","KABUPATEN BARITO KUALA"));
        list.add(new Tuple("6305","KABUPATEN TAPIN"));
        list.add(new Tuple("6306","KABUPATEN HULU SUNGAI SELATAN"));
        list.add(new Tuple("6307","KABUPATEN HULU SUNGAI TENGAH"));
        list.add(new Tuple("6308","KABUPATEN HULU SUNGAI UTARA"));
        list.add(new Tuple("6309","KABUPATEN TABALONG"));
        list.add(new Tuple("6310","KABUPATEN TANAH BUMBU"));
        list.add(new Tuple("6311","KABUPATEN BALANGAN"));
        list.add(new Tuple("6371","KOTA BANJARMASIN"));
        list.add(new Tuple("6372","KOTA BANJAR BARU"));
        cityRegencies.put("63", list);

        list = new ArrayList<>();
        list.add(new Tuple("6401","KABUPATEN PASER"));
        list.add(new Tuple("6402","KABUPATEN KUTAI BARAT"));
        list.add(new Tuple("6403","KABUPATEN KUTAI KARTANEGARA"));
        list.add(new Tuple("6404","KABUPATEN KUTAI TIMUR"));
        list.add(new Tuple("6405","KABUPATEN BERAU"));
        list.add(new Tuple("6409","KABUPATEN PENAJAM PASER UTARA"));
        list.add(new Tuple("6411","KABUPATEN MAHAKAM HULU"));
        list.add(new Tuple("6471","KOTA BALIKPAPAN"));
        list.add(new Tuple("6472","KOTA SAMARINDA"));
        list.add(new Tuple("6474","KOTA BONTANG"));
        cityRegencies.put("64", list);

        list = new ArrayList<>();
        list.add(new Tuple("6501","KABUPATEN MALINAU"));
        list.add(new Tuple("6502","KABUPATEN BULUNGAN"));
        list.add(new Tuple("6503","KABUPATEN TANA TIDUNG"));
        list.add(new Tuple("6504","KABUPATEN NUNUKAN"));
        list.add(new Tuple("6571","KOTA TARAKAN"));
        cityRegencies.put("65", list);

        list = new ArrayList<>();
        list.add(new Tuple("7101","KABUPATEN BOLAANG MONGONDOW"));
        list.add(new Tuple("7102","KABUPATEN MINAHASA"));
        list.add(new Tuple("7103","KABUPATEN KEPULAUAN SANGIHE"));
        list.add(new Tuple("7104","KABUPATEN KEPULAUAN TALAUD"));
        list.add(new Tuple("7105","KABUPATEN MINAHASA SELATAN"));
        list.add(new Tuple("7106","KABUPATEN MINAHASA UTARA"));
        list.add(new Tuple("7107","KABUPATEN BOLAANG MONGONDOW UTARA"));
        list.add(new Tuple("7108","KABUPATEN SIAU TAGULANDANG BIARO"));
        list.add(new Tuple("7109","KABUPATEN MINAHASA TENGGARA"));
        list.add(new Tuple("7110","KABUPATEN BOLAANG MONGONDOW SELATAN"));
        list.add(new Tuple("7111","KABUPATEN BOLAANG MONGONDOW TIMUR"));
        list.add(new Tuple("7171","KOTA MANADO"));
        list.add(new Tuple("7172","KOTA BITUNG"));
        list.add(new Tuple("7173","KOTA TOMOHON"));
        list.add(new Tuple("7174","KOTA KOTAMOBAGU"));
        cityRegencies.put("71", list);

        list = new ArrayList<>();
        list.add(new Tuple("7201","KABUPATEN BANGGAI KEPULAUAN"));
        list.add(new Tuple("7202","KABUPATEN BANGGAI"));
        list.add(new Tuple("7203","KABUPATEN MOROWALI"));
        list.add(new Tuple("7204","KABUPATEN POSO"));
        list.add(new Tuple("7205","KABUPATEN DONGGALA"));
        list.add(new Tuple("7206","KABUPATEN TOLI-TOLI"));
        list.add(new Tuple("7207","KABUPATEN BUOL"));
        list.add(new Tuple("7208","KABUPATEN PARIGI MOUTONG"));
        list.add(new Tuple("7209","KABUPATEN TOJO UNA-UNA"));
        list.add(new Tuple("7210","KABUPATEN SIGI"));
        list.add(new Tuple("7211","KABUPATEN BANGGAI LAUT"));
        list.add(new Tuple("7212","KABUPATEN MOROWALI UTARA"));
        list.add(new Tuple("7271","KOTA PALU"));
        cityRegencies.put("72", list);

        list = new ArrayList<>();
        list.add(new Tuple("7301","KABUPATEN KEPULAUAN SELAYAR"));
        list.add(new Tuple("7302","KABUPATEN BULUKUMBA"));
        list.add(new Tuple("7303","KABUPATEN BANTAENG"));
        list.add(new Tuple("7304","KABUPATEN JENEPONTO"));
        list.add(new Tuple("7305","KABUPATEN TAKALAR"));
        list.add(new Tuple("7306","KABUPATEN GOWA"));
        list.add(new Tuple("7307","KABUPATEN SINJAI"));
        list.add(new Tuple("7308","KABUPATEN MAROS"));
        list.add(new Tuple("7309","KABUPATEN PANGKAJENE DAN KEPULAUAN"));
        list.add(new Tuple("7310","KABUPATEN BARRU"));
        list.add(new Tuple("7311","KABUPATEN BONE"));
        list.add(new Tuple("7312","KABUPATEN SOPPENG"));
        list.add(new Tuple("7313","KABUPATEN WAJO"));
        list.add(new Tuple("7314","KABUPATEN SIDENRENG RAPPANG"));
        list.add(new Tuple("7315","KABUPATEN PINRANG"));
        list.add(new Tuple("7316","KABUPATEN ENREKANG"));
        list.add(new Tuple("7317","KABUPATEN LUWU"));
        list.add(new Tuple("7318","KABUPATEN TANA TORAJA"));
        list.add(new Tuple("7322","KABUPATEN LUWU UTARA"));
        list.add(new Tuple("7325","KABUPATEN LUWU TIMUR"));
        list.add(new Tuple("7326","KABUPATEN TORAJA UTARA"));
        list.add(new Tuple("7371","KOTA MAKASSAR"));
        list.add(new Tuple("7372","KOTA PAREPARE"));
        list.add(new Tuple("7373","KOTA PALOPO"));
        cityRegencies.put("73", list);

        list = new ArrayList<>();
        list.add(new Tuple("7401","KABUPATEN BUTON"));
        list.add(new Tuple("7402","KABUPATEN MUNA"));
        list.add(new Tuple("7403","KABUPATEN KONAWE"));
        list.add(new Tuple("7404","KABUPATEN KOLAKA"));
        list.add(new Tuple("7405","KABUPATEN KONAWE SELATAN"));
        list.add(new Tuple("7406","KABUPATEN BOMBANA"));
        list.add(new Tuple("7407","KABUPATEN WAKATOBI"));
        list.add(new Tuple("7408","KABUPATEN KOLAKA UTARA"));
        list.add(new Tuple("7409","KABUPATEN BUTON UTARA"));
        list.add(new Tuple("7410","KABUPATEN KONAWE UTARA"));
        list.add(new Tuple("7411","KABUPATEN KOLAKA TIMUR"));
        list.add(new Tuple("7412","KABUPATEN KONAWE KEPULAUAN"));
        list.add(new Tuple("7413","KABUPATEN MUNA BARAT"));
        list.add(new Tuple("7414","KABUPATEN BUTON TENGAH"));
        list.add(new Tuple("7415","KABUPATEN BUTON SELATAN"));
        list.add(new Tuple("7471","KOTA KENDARI"));
        list.add(new Tuple("7472","KOTA BAUBAU"));
        cityRegencies.put("74", list);

        list = new ArrayList<>();
        list.add(new Tuple("7501","KABUPATEN BOALEMO"));
        list.add(new Tuple("7502","KABUPATEN GORONTALO"));
        list.add(new Tuple("7503","KABUPATEN POHUWATO"));
        list.add(new Tuple("7504","KABUPATEN BONE BOLANGO"));
        list.add(new Tuple("7505","KABUPATEN GORONTALO UTARA"));
        list.add(new Tuple("7571","KOTA GORONTALO"));
        cityRegencies.put("75", list);

        list = new ArrayList<>();
        list.add(new Tuple("7601","KABUPATEN MAJENE"));
        list.add(new Tuple("7602","KABUPATEN POLEWALI MANDAR"));
        list.add(new Tuple("7603","KABUPATEN MAMASA"));
        list.add(new Tuple("7604","KABUPATEN MAMUJU"));
        list.add(new Tuple("7605","KABUPATEN MAMUJU UTARA"));
        list.add(new Tuple("7606","KABUPATEN MAMUJU TENGAH"));
        cityRegencies.put("76", list);

        list = new ArrayList<>();
        list.add(new Tuple("8101","KABUPATEN MALUKU TENGGARA BARAT"));
        list.add(new Tuple("8102","KABUPATEN MALUKU TENGGARA"));
        list.add(new Tuple("8103","KABUPATEN MALUKU TENGAH"));
        list.add(new Tuple("8104","KABUPATEN BURU"));
        list.add(new Tuple("8105","KABUPATEN KEPULAUAN ARU"));
        list.add(new Tuple("8106","KABUPATEN SERAM BAGIAN BARAT"));
        list.add(new Tuple("8107","KABUPATEN SERAM BAGIAN TIMUR"));
        list.add(new Tuple("8108","KABUPATEN MALUKU BARAT DAYA"));
        list.add(new Tuple("8109","KABUPATEN BURU SELATAN"));
        list.add(new Tuple("8171","KOTA AMBON"));
        list.add(new Tuple("8172","KOTA TUAL"));
        cityRegencies.put("81", list);

        list = new ArrayList<>();
        list.add(new Tuple("8201","KABUPATEN HALMAHERA BARAT"));
        list.add(new Tuple("8202","KABUPATEN HALMAHERA TENGAH"));
        list.add(new Tuple("8203","KABUPATEN KEPULAUAN SULA"));
        list.add(new Tuple("8204","KABUPATEN HALMAHERA SELATAN"));
        list.add(new Tuple("8205","KABUPATEN HALMAHERA UTARA"));
        list.add(new Tuple("8206","KABUPATEN HALMAHERA TIMUR"));
        list.add(new Tuple("8207","KABUPATEN PULAU MOROTAI"));
        list.add(new Tuple("8208","KABUPATEN PULAU TALIABU"));
        list.add(new Tuple("8271","KOTA TERNATE"));
        list.add(new Tuple("8272","KOTA TIDORE KEPULAUAN"));
        cityRegencies.put("82", list);

        list = new ArrayList<>();
        list.add(new Tuple("9101","KABUPATEN FAKFAK"));
        list.add(new Tuple("9102","KABUPATEN KAIMANA"));
        list.add(new Tuple("9103","KABUPATEN TELUK WONDAMA"));
        list.add(new Tuple("9104","KABUPATEN TELUK BINTUNI"));
        list.add(new Tuple("9105","KABUPATEN MANOKWARI"));
        list.add(new Tuple("9106","KABUPATEN SORONG SELATAN"));
        list.add(new Tuple("9107","KABUPATEN SORONG"));
        list.add(new Tuple("9108","KABUPATEN RAJA AMPAT"));
        list.add(new Tuple("9109","KABUPATEN TAMBRAUW"));
        list.add(new Tuple("9110","KABUPATEN MAYBRAT"));
        list.add(new Tuple("9111","KABUPATEN MANOKWARI SELATAN"));
        list.add(new Tuple("9112","KABUPATEN PEGUNUNGAN ARFAK"));
        list.add(new Tuple("9171","KOTA SORONG"));
        cityRegencies.put("91", list);

        list = new ArrayList<>();
        list.add(new Tuple("9401","KABUPATEN MERAUKE"));
        list.add(new Tuple("9402","KABUPATEN JAYAWIJAYA"));
        list.add(new Tuple("9403","KABUPATEN JAYAPURA"));
        list.add(new Tuple("9404","KABUPATEN NABIRE"));
        list.add(new Tuple("9408","KABUPATEN KEPULAUAN YAPEN"));
        list.add(new Tuple("9409","KABUPATEN BIAK NUMFOR"));
        list.add(new Tuple("9410","KABUPATEN PANIAI"));
        list.add(new Tuple("9411","KABUPATEN PUNCAK JAYA"));
        list.add(new Tuple("9412","KABUPATEN MIMIKA"));
        list.add(new Tuple("9413","KABUPATEN BOVEN DIGOEL"));
        list.add(new Tuple("9414","KABUPATEN MAPPI"));
        list.add(new Tuple("9415","KABUPATEN ASMAT"));
        list.add(new Tuple("9416","KABUPATEN YAHUKIMO"));
        list.add(new Tuple("9417","KABUPATEN PEGUNUNGAN BINTANG"));
        list.add(new Tuple("9418","KABUPATEN TOLIKARA"));
        list.add(new Tuple("9419","KABUPATEN SARMI"));
        list.add(new Tuple("9420","KABUPATEN KEEROM"));
        list.add(new Tuple("9426","KABUPATEN WAROPEN"));
        list.add(new Tuple("9427","KABUPATEN SUPIORI"));
        list.add(new Tuple("9428","KABUPATEN MAMBERAMO RAYA"));
        list.add(new Tuple("9429","KABUPATEN NDUGA"));
        list.add(new Tuple("9430","KABUPATEN LANNY JAYA"));
        list.add(new Tuple("9431","KABUPATEN MAMBERAMO TENGAH"));
        list.add(new Tuple("9432","KABUPATEN YALIMO"));
        list.add(new Tuple("9433","KABUPATEN PUNCAK"));
        list.add(new Tuple("9434","KABUPATEN DOGIYAI"));
        list.add(new Tuple("9435","KABUPATEN INTAN JAYA"));
        list.add(new Tuple("9436","KABUPATEN DEIYAI"));
        list.add(new Tuple("9471","KOTA JAYAPURA"));
        cityRegencies.put("94", list);
    }

    public static List<Tuple> getCityRegencies(String provinceKey){
        return cityRegencies.get(provinceKey);
    }
}
